### ISSUE TITLE
feature specification

### ISSUE THREAD

**Issue by alanyuchenhou** [yuchenhou/athanasea#25]
This issue is for all of us. To specify features, I think we'll use a language called [gherkin](http://docs.behat.org/en/v2.5/guides/1.gherkin.html). That pages loads very slow but it provides a good introduction to gherkin. It's very precise and easy to use and worth the time learning it. Hope you'll enjoy it!

**Comment by Taxidea-Jen** [comment]
I started reading through the page you posted the link to, and then I stopped because it seems too complicated for what I want.  It's fine if you developers want to use it, but I just want to be able to write descriptions of what I want for the site in English and not have to use particular code words or whatever this gherkin thing is.

**Comment by Taxidea-Jen** [comment]
I updated one section of the roadmap wiki to give an example of what I want to have happen for the "rescue" portion of the site.  Also so you can see why I think using gherkin would not be good for me.

**Comment by alanyuchenhou** [comment]
Sorry to hear that. In this case, I'll submit feature requests based on what I understand about your requirement. I think you'll get familiar with it very soon after seeing a few issues, which I'll submit soon. Actually Gherkin is very friendly and supposed to be bridge the gap between tech and non-technical world.
